### ISSUE TITLE
Introduce Categories

### ISSUE THREAD

**Issue by sunnyjindal** [the-canonizer/canonizer-3.0-api#1023]
We need to introduce the concept of categories within the system. The system should have the ability to:
- admin should be able to manage categories from backend panel.
- Any category marked as inactive should not be available in the API.
- The user can associate a topic and camp with zero or multiple categories (change existing APIs)
- An API is required to list the categories.
- An API is required to list all topics/camps according to the category.

**Comment by sajid315** [comment]
For the above requirement , changes have been done. Following are the PR's

https://github.com/the-canonizer/canonizer-3.0-api/pull/1035
https://github.com/the-canonizer/canonizer3-admin/pull/75

**Comment by sajid315** [comment]
@rupalichavan9860 
This ticket was made for the requirement of tags implementation. 
So the tags module has been added at the admin side. And also we are handling active/in-active of the tags there.

API to list down the active tags on our public site also have been made.
