### ISSUE TITLE
"Something went wrong" when navigate to "Topic Detail" page

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/canonizer-3.0-api#1039]
When user navigate to "Topic Detail" page "Something went wrong" error occurred. 

As shown in attached screenshot below:

![Image](https://github.com/the-canonizer/canonizer-3.0-api/assets/120023458/0f32919f-30f0-4afe-bb9c-d683a470a59e)

![Image](https://github.com/the-canonizer/canonizer-3.0-api/assets/120023458/db71ea68-7cf6-4fd3-adeb-7a45f71e74d7)

**Comment by array-junkie** [comment]
This is fixed. PR https://github.com/the-canonizer/canonizer-3.0-api/pull/1041

**Comment by rupalichavan9860** [comment]
Working fine on development server

**Comment by rupalichavan9860** [comment]
Verified on live
