### ISSUE TITLE
Migrate from legacy FCM APIs to HTTP v1

### ISSUE THREAD

**Issue by array-junkie** [the-canonizer/canonizer-3.0-api#1045]
We need to Migrate from legacy FCM APIs to HTTP v1 because legacy is deprecated on June 20, 2023, and will be removed on June 21, 2024.

For more: https://firebase.google.com/docs/cloud-messaging/migrate-v1?hl=en&authuser=0

**Comment by DevAlchemyCD** [comment]
PR : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1842

**Comment by array-junkie** [comment]
Hotfix for production is also attached to this issue.
