### ISSUE TITLE
Get Sibling Camp List

### ISSUE THREAD

**Issue by sunnyjindal** [the-canonizer/canonizer-3.0-api#1049]
For camp detail page, we need to create the API that will list the siblings of the selected camp.

**Comment by sajid315** [comment]
Functionality code is pushed under the following branch "[feature/sibling-camps-1049](https://github.com/the-canonizer/canonizer-3.0-api/tree/feature/sibling-camps-1049)". Following is the API END POINT, 

```
POST
Authorization Bearer Token
{{API_URL}}/api/v3/get-sibling-camps

{
    "topic_num":1495,
    "camp_num":6,
    "parent_camp_num": 3
}
```

**Comment by sajid315** [comment]
Unit Test cases for this ticket are also done under attached PR with this ticket.

**Comment by sajid315** [comment]
@rupalichavan9860 
This ticket was made to implement sibling camps of the current camp as per proposed in the figma design. 
API has been done and also its working on ux-dev server. 
We can move this ticket ahead.
