### ISSUE TITLE
Support API's updates for UI/UX

### ISSUE THREAD

**Issue by sajid315** [the-canonizer/canonizer-3.0-api#1100]
As discussed with @nalwa and Twinkle in the call about Figma updates in support module. We need to do the API response updates according to the UI requirements.

Support Parent Camp
https://www.figma.com/design/GqRitUIyR77zZOmeSA1BsY/Canonizer-%3CUX-enhancement%3E?node-id=282-16500&t=KeBn72FXu6MDzxIm-0

Support Child L0 Camp
https://www.figma.com/design/GqRitUIyR77zZOmeSA1BsY/Canonizer-%3CUX-enhancement%3E?node-id=282-16503&t=KeBn72FXu6MDzxIm-0

Support Child L1 Camp
https://www.figma.com/design/GqRitUIyR77zZOmeSA1BsY/Canonizer-%3CUX-enhancement%3E?node-id=282-16506&t=KeBn72FXu6MDzxIm-0

Support Parent Camp Again
https://www.figma.com/design/GqRitUIyR77zZOmeSA1BsY/Canonizer-%3CUX-enhancement%3E?node-id=282-16510&t=KeBn72FXu6MDzxIm-0

https://www.figma.com/design/GqRitUIyR77zZOmeSA1BsY/Canonizer-%3CUX-enhancement%3E?node-id=282-24991&t=KeBn72FXu6MDzxIm-0

https://www.figma.com/design/GqRitUIyR77zZOmeSA1BsY/Canonizer-%3CUX-enhancement%3E?node-id=282-16522&t=KeBn72FXu6MDzxIm-0

**Comment by sajid315** [comment]
@nalwa all of the pushed code from your end is merged and tested at our side. Moving this ticket ahead.

**Comment by saniatg** [comment]
functionality and the messages are working fine on UX server
@sunnyjindal  Twinkle will need to update the design , as the message in the figma is incorrect , ALSO THE CAMP NAME

![Screenshot 2024-11-06 at 6 47 36 PM](https://github.com/user-attachments/assets/4da81f78-a4d8-44bb-a03d-1ac3eb38e7b8)
