### ISSUE TITLE
There is no button for "Manage Statement "on "Topic Detail" page

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/canonizer-3.0-api#1122]
Steps:
User creates a "topic" and add "statement" in it
User adds statement and publish it
User is now on "Statement History" page where user commit change
Then user clicks on agreement in breadcrumb and navigate to "topic detail" page again

Once user is on "topic detail" page it is not possible for user to navigate back to "Statement History" page.

There must be any button for user to navigate back to "Statement History" page

**Comment by array-junkie** [comment]
@hassaanCD It is implemented in [#1325](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/issues/1325) ticket. Could you verify it and move the ticket?

**Comment by hassaanCD** [comment]
Verified

**Comment by rupalichavan9860** [comment]
Verified on live
