### ISSUE TITLE
Remove un-necessary params from objection api 

### ISSUE THREAD

**Issue by DevAlchemyCD** [the-canonizer/canonizer-3.0-api#1152]
Endpoint: api/v3/manage-camp

![Image](https://github.com/user-attachments/assets/8cc888ea-2040-45ed-9dd2-9e9fffb9d94f)

**Comment by sajid315** [comment]
@rupalichavan9860 
That ticket was made to exclude the API param for event type objection. Its implemented and working on ux-dev server.
