### ISSUE TITLE
Display on topics that are linked with active tags

### ISSUE THREAD

**Issue by sajid315** [the-canonizer/canonizer-3.0-api#1153]
On Ux-dev environment , in preferred topics there are some of topics having in-active tags as shown in below screenshot.

![Image](https://github.com/user-attachments/assets/b7ff3385-c306-4dad-85de-dc4d16cb047f)

Right now below are the active tags,

![Image](https://github.com/user-attachments/assets/b0f90714-7b44-41f9-92bd-2e494e089b97)

Expected Results: we should show only those topics having active tags and linked with these topics.

**Comment by sajid315** [comment]
@saniatg Now only those tags will be shown that are active from admin panel.

**Comment by rupalichavan9860** [comment]
![image](https://github.com/user-attachments/assets/e771f473-0b6d-4593-8759-6f75f1bb8fed)

Please check the same for FEATURED TOPICS

**Comment by sajid315** [comment]
@rupalichavan9860 I added the same logic for featured topics as well, now only active tags will be shown. 
Have a look please.

**Comment by rupalichavan9860** [comment]
Yes @sajid315 Working fine now

**Comment by rupalichavan9860** [comment]
Verified on live
