### ISSUE TITLE
Activity logger not working for mentioned activities

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/canonizer-3.0-api#400]
Here's the list of activities for those activity logger is not working

1.  thread create
2.  thread updated
3.  post add
4.  post edited
5. remove delegated support
6. statement add
7. statement update

**Comment by sajid315** [comment]
For remove delegated support , I created a ticket and assigned to Reena.
https://github.com/the-canonizer/canonizer-3.0-api/issues/426

**Comment by sajid315** [comment]
Raised PR is, 
https://github.com/the-canonizer/canonizer-3.0-api/pull/430

**Comment by subhancd** [comment]
working on staging.

**Comment by subhancd** [comment]
working fine on beta
