### ISSUE TITLE
Images submitted on beta don't really seem to be there.

### ISSUE THREAD

**Issue by mark-shamy** [the-canonizer/canonizer-3.0-api#489]
![Image](https://user-images.githubusercontent.com/6559312/209482842-79f14b7b-fccf-43f3-93af-6f1aa24b0535.png)

I inserted the TsesVolumetricWorm.png file on beta.
It looks like the file is there both on Beta, and on live.
However, the short code link doesn't work, as if the file isn't really there.
file:https://canonizer.com/files/TsesVolumetricWorm.png

This is a critical issue.

Also, you can't use "_" in the file names, and I am assuming you can't use other special characters.
We should be able to use all special characters in all record fields like this.
We just need to make sure they are properly escaped to prevent SQL injection.

**Comment by rupalichavan9860** [comment]
Verified by Ashutosh
