### ISSUE TITLE
Add new Consciousness video provided (Update Video API Seeder)

### ISSUE THREAD

**Issue by array-junkie** [the-canonizer/canonizer-3.0-api#522]
- Add this [https://canonizer.com/static/videos/consciousness/The_world_in_you_head_360.mp4] video in the seed at the 4th index.

**Comment by array-junkie** [comment]
Code merged on staging. Working fine on staging.

**Comment by rupalichavan9860** [comment]
Verified by Ashutosh

**Comment by rupalichavan9860** [comment]
Verified on live by @akuks
