### ISSUE TITLE
Protect the public APIs of Canonizer using client key.

### ISSUE THREAD

**Issue by ashish76** [the-canonizer/canonizer-3.0-api#531]
Currently, all the APIs that do not require a user to be authenticated are publically exposed. This might cause a potential threat to the server. 

We have to provide a mechanism to protect the usage of such APIs and make sure that only the authorized can only have the access to these.  For example, in the present state, the Canoniozer application will be the only client to access those APIs.

**Comment by rupalichavan9860** [comment]
Verified by Ashutosh
