### ISSUE TITLE
Topic is not creating on staging

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/canonizer-3.0-api#567]
![Image](https://user-images.githubusercontent.com/120023458/222717743-c2b6040d-3350-42ba-bba3-0c176a62229e.png)

**Comment by ks-rahul** [comment]
@hassaanCD  one migration is not run on the staging that's why this issue is caused. please check now.

**Comment by hassaanCD** [comment]
@ks-rahul It is working fine on staging now.

**Comment by saniatg** [comment]
@rupalichavan9860 working fine on staging

**Comment by rupalichavan9860** [comment]
Verified on live
