### ISSUE TITLE
Error on topic detail page

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/canonizer-3.0-api#572]
Steps to reproduce

Go to any topic detail page
Copy the URL
Open private window and paste the copied URL
Topic and camp name are blank as shown in attached screenshot:

![Image](https://user-images.githubusercontent.com/120023458/223964873-ec585cff-9401-4ccd-b13c-de407b41794b.png)

**Comment by saniatg** [comment]
Working fine on staging

**Comment by saniatg** [comment]
Working fine on production
