### ISSUE TITLE
Camp Archive

### ISSUE THREAD

**Issue by mark-shamy** [the-canonizer/canonizer-3.0-api#574]
Frontend companion issue https://github.com/the-canonizer/canonizer-3.0-frontend/issues/862

Expected behavior upon camp archival; if their are any supporters of the camp, the 24 hour review process will be in affect. After review period, a Boolean fields on the camp "isArchived" and  "directArchive" will be set to true. Expected behavior upon camp restoration; initiate review period behavior, if review is accepted, set the "isArchived" and "directArchive" field to false and change the support order of each supporters to be at the _end_ of their support list.

No data of the camp other than the Boolean field will be modified when a camp is archived. When serving requests to the front end or Canonizer service, unless specified by the client, camps that are archived should be skipped to create the effect as if they were not there. Algorithms.php will need to be modified to skip achieved camps will computing scores. 

When archiving a camp with children, traverse all of it's children setting it's "isArchived" field to true, this way when unarchiving a camp, sub camps that were previously archived will not be reactivated by only setting "isArchived" to false on camps where "directArchive" is also false.

Archiving the agreement camp should have the affect of archiving the topic. When client requests a topic list, unless specified, do not return topics with archived agreement camps.

**Comment by nalwa** [comment]
ok @mark-shamy  as per my understanding this feature will have below  implementation in terms of development:

1. Review period to be initiated on archiving or restoration of archived camp. if camp has sub-camps then that should be archived by setting "is_archived" True and "direct_archive" As false.  (with email - proposed change email)
 
2.  Support will be removed from camp including sub-camps on archiving.

3. On restoration of archiving camp support order will be last support of supporter list. (including sub-camps).  
  [In review period will take place in this case as well. Also proposed change email will be sent]
 
5. Score calculation changes in service API. will not include archived camps until or unless "archived" option is checked by user from filters.

6. In case of archiving agreement camp topic API will not fetch that topic through out the application unless user selects Include Archived from filters.

@mark-shamy  please let me know if  i misunderstood anything.

**Comment by nalwa** [comment]
@mark-shamy  and @rupalichavan9860  i have below query on this:

Scenario: 
1. User A supporting "camp A" child camp of "Agreement" is archived and agreed by all supporter, So support of user A is end for "camp A".

2. Then user A start supporting "agreement" camp.
3. Now, "camp A" is restored.
4. what will be support of "user A" in "camp A" ? 

So, basically question is what will happen to support of such camps on restoration when support is being added to parent or grand parent.

**Comment by rupalichavan9860** [comment]
@nalwa @mark-shamy 
For example, if the user supports the following two camps: "camp 1" and "camp 2," and changes "camp 2's" parent to "camp 1,"

According to functionality as it currently exists, support is added to child camp while parent camp support is removed.

I believe that in the above scenario, if the camp is unarchived, the score should be restored for the subcamp and removed from the parent camp.

@mark-shamy @BrentAllsop  Please let me know your thoughts on this

**Comment by rupalichavan9860** [comment]
As functionality has been implemented and we are logging issues separately, we are closing this.
