### ISSUE TITLE
Camp editor resizable

### ISSUE THREAD

**Issue by mark-shamy** [the-canonizer/canonizer-3.0-api#575]
Add "resize: vertical" style attribute to camp editor text area

**Comment by ks-rahul** [comment]
@mark-shamy I checked that issue it seems to work as you mentioned 

![Image](https://user-images.githubusercontent.com/95217406/224682671-0c1d200f-4e9a-41ed-87e7-38771308e394.png)

if it is not desired behavior please explain it more.

**Comment by ashish76** [comment]
@ ks-rahul It is the WYSIWYG editor implemented in the statement.  @mark-shamy  correct me if I am wrong.

**Comment by mark-shamy** [comment]
@ashish76 I should have been more specific, I was referring to statement editor, not the edit summary.

**Comment by saniatg** [comment]
@ks-rahul The editor gets stuck at a particular area when dragged vertically.
I added one line statement then dragged vertically , the I left the cursor and typed something in Edit summary field"
Now when I try to resize the editor back upwards, it is not working.
![Screenshot 2023-03-22 at 6 17 54 PM](https://user-images.githubusercontent.com/91254708/226909722-3f2e3e85-3ce2-4f75-a3b7-43b650e9a20a.png)

**Comment by ks-rahul** [comment]
@saniatg I'm not able to reproduce this issue. could you please check again

**Comment by rupalichavan9860** [comment]
@ks-rahul Working fine on both staging and live
