### ISSUE TITLE
Terminology for events

### ISSUE THREAD

**Issue by sajid315** [the-canonizer/canonizer-3.0-api#576]
There are states to go through when modifying a topic record / camp record / statement.
1. Submitted (but not yet committed)  Never do any notification in this state.
          a)  The user should have a chance to cancel the operation, or after 1 hour, the actual submit occurs.
          b)  No notification done till the "actual submit" is achieved.
2. Actual submit
          a)  Notifications go out to supporters and to the recent activities list.
          b) Terminology: "<nick name id> proposed a change to [topic | camp | statement]: <one of the following on a new line>
                   i  topic case:  Topic: <topic name>.
                   ii camp case: Topic <topic name> camp <camp name>.
                   iii statement case: Topic <topic name> camp  <camp name>.
          c) The entire entry will be a link.

**Comment by sajid315** [comment]
Frontend code for this ticket needs to be deployed #867. Moving this ticket back as discussed with Sania.

**Comment by sajid315** [comment]
@M-Darab  Topic and camp name are missing, 


![Image](https://user-images.githubusercontent.com/111273633/226585402-2c8a462c-f32b-4c8a-8454-28a1f78e4cc0.png)

**Comment by array-junkie** [comment]
@BrentAllsop For the point 1.a that specifying : "The user should have a chance to cancel the operation, or after 1 hour, the actual submit occurs.". 
So it means for every change either topic/camp/statement we will introduce the (Cancel operation/ Discard button) with Commit button until the change is not committed. So we will simply delete the record. 
Is it fine?

**Comment by array-junkie** [comment]
@rupalichavan9860 @BrentAllsop According to the today's discussion, We will place a "Cancel" button next to the "Commit" button. This "Cancel" button will only displayed when the change is in grace period(not yet committed). When the button is clicked, it will simply delete the record from the database.
 
Yes? Correct me if I'm wrong.

**Comment by array-junkie** [comment]
https://github.com/the-canonizer/canonizer-3.0-api/issues/596

I made a separate ticket for Point 1.a. Other than that, all the other points mentioned in this ticket are done. So I'm moving this ticket to deploy on staging

**Comment by BrentAllsop** [comment]
> @rupalichavan9860 @BrentAllsop According to the today's discussion, We will place a "Cancel" button next to the "Commit" button. This "Cancel" button will only displayed when the change is in grace period(not yet committed). When the button is clicked, it will simply delete the record from the database.
> 
> Yes? Correct me if I'm wrong.

Yes.  As a rule, we never modify history, only supersede it with a newer version of the record.
But in this case, history hasn't been made, yet.  Nobody sees it, and nobody knows about it, till the commit button is pressed, or the 1 hour grace period expires.  Until it becomes history (someone can see it, or is notified) it can be deleted from the db.

**Comment by rupalichavan9860** [comment]
Verified By Ashutosh
