### ISSUE TITLE
Include review isn't working.

### ISSUE THREAD

**Issue by sajid315** [the-canonizer/canonizer-3.0-api#577]
You can see in the history there is a new version of the statement that is not yet live:

![Image](https://user-images.githubusercontent.com/6559312/224171627-e4953273-2847-487a-a305-aba7dd31d590.png)

Yet as you can see here, when the "include review" option is selected, it doesn't display the in review version of the statement.

![Image](https://user-images.githubusercontent.com/6559312/224171771-711dd197-023f-442e-be1d-94babcaa0c59.png)

**Comment by sajid315** [comment]
@BrentAllsop @rupalichavan9860 
I have checked the same topic "United Utah Party Platform" , now the statement is live.

Also I did a test case for in review changes. Made a topic and submitted change from other user to be in review. 
And here below are the results that is fine.

@rupalichavan9860 can you also have a look please ?
![image](https://user-images.githubusercontent.com/111273633/224933786-631a2071-3a3e-4d71-bf04-02d39ac291bd.png)

**Comment by rupalichavan9860** [comment]
@BrentAllsop may have checked this before committing changes. Brent, could you please confirm?

**Comment by BrentAllsop** [comment]
Yes, I can't seem to reproduce this issue.
So I guess it would be fine with me if we close this issue.
