### ISSUE TITLE
Backend Update response for subscription list

### ISSUE THREAD

**Issue by sajid315** [the-canonizer/canonizer-3.0-api#581]
Linked with 
https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/issues/219

**Comment by sajid315** [comment]
Raised PR 
https://github.com/the-canonizer/canonizer-3.0-api/pull/582

**Comment by rupalichavan9860** [comment]
Verified on staging

**Comment by rupalichavan9860** [comment]
Verified on live
