### ISSUE TITLE
Recent activities items should be a hot link to the actual activity.

### ISSUE THREAD

**Issue by array-junkie** [the-canonizer/canonizer-3.0-api#590]
And include far more information, like the name of the topic and camp.

**Comment by rupalichavan9860** [comment]
Verified on staging

**Comment by SandeepTalentelgia** [comment]
Not Fixed, verified over the live server.

**Comment by SandeepTalentelgia** [comment]
Closed, verified over the live server, As discussed with Rupali, it should only implement on the home page.

**Comment by rupalichavan9860** [comment]
Verified on live
