### ISSUE TITLE
The user should have a chance to cancel the operation, or after 1 hour, the actual submit occurs.

### ISSUE THREAD

**Issue by array-junkie** [the-canonizer/canonizer-3.0-api#596]
We will place a "Cancel" button next to the "Commit" button. This "Cancel" button will only displayed when the change is in grace period(not yet committed). When the button is clicked, it will simply delete the record from the database. 

We never modify history, only supersede it with a newer version of the record. But in this case, history hasn't been made, yet. Nobody sees it, and nobody knows about it, till the commit button is pressed, or the 1 hour grace period expires. Until it becomes history (someone can see it, or is notified) it can be deleted from the db.

**Comment by array-junkie** [comment]
**Acceptance criteria** (By @rupalichavan9860)

**User Story** : The user should have a chance to cancel the operation, or after 1 hour, the actual submit occurs

**Scenario 1** : The "Cancel" button should appear next to the "Commit" button for the submitter.
Given : User A directly supports the camp;
And : User B proposed changing the topic, camp, or statement; Changes have not yet been committed.
Then : The "Cancel" button should appear next to the "Commit" button for the submitter.

**Scenario 2** : The "Cancel" button should appear next to the "Commit" button for the submitter.
Given : User A directly supports the camp;
And : User B proposed changing the topic, camp, or statement; Changes have not yet been committed.
When : User B makes the necessary adjustments(Edit Change) and submits them.
Then : The "Cancel" button should appear next to the "Commit" button for the submitter.

**Scenario 3** : The "Cancel" button should not appear for the submitter.
Given : User A directly supports the camp;
And : User B proposed changing the topic, camp, or statement; Changes have not yet been committed.
When : When the one-hour grace period is up
Then : The submitted modification should be committed and the "Commit" and "Cancel" buttons should be hidden.    

**Scenario 4** : The "Cancel" button should not appear for the submitter.
Given : User A directly supports the camp;
And : User B proposed changing the topic, camp, or statement; Changes have not yet been committed.
When : User B makes the necessary adjustments(Edit Change) and submits them.
And : The one-hour grace period is up
Then : The submitted modification should be committed and the "Commit" and "Cancel" buttons should be hidden.  

**Scenario 5** : The "Cancel" button should not appear for the submitter.
Given : User A directly supports the camp;
And : User B proposed changing the topic, camp, or statement; Changes have not yet been committed.
When : User B makes the necessary adjustments(Edit Change) and submits them.
And : User B comitted the changes
Then : The "Cancel" buttons should be hidden.

**Comment by rupalichavan9860** [comment]
Closing this because functionality has been implemented. If there are any problems, we will log them.

**Comment by rupalichavan9860** [comment]
Verified on live
