### ISSUE TITLE
Replace / from the namespace with > to display the hierarchy of the Namespace.

### ISSUE THREAD

**Issue by ashish76** [the-canonizer/canonizer-3.0-api#623]
In the Namespace dropdown, we have to replace the forward slash (/) with the arrow symbol to display the hierarchy of the Namespace. 
Example
- General
- Organisation > Canonizer
- Family > Jesperson_Oscar_F

Note: there should not be any leading or trailing forward slash

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by rupalichavan9860** [comment]
Verified on live
