### ISSUE TITLE
AgreetoChange API must respond in specific scenario

### ISSUE THREAD

**Issue by sajid315** [the-canonizer/canonizer-3.0-api#639]
Steps to produce:
1- User A is the supporter of camp.
2- User B added the support in camp.
3- User C submit and commit a change. 
4- Now both User A & B can agree or object.
5- User B agreed the change. 
6- Now When User A agreed it will go live but at the same time if User B disagreed again. Then API responding error.

Below is the screenshot.

![Image](https://user-images.githubusercontent.com/111273633/236146869-6996e641-aba8-46c6-a00c-944622add250.png)

**Comment by sandeeptlgt** [comment]
Closed, verified on live.
