### ISSUE TITLE
Change should be live in that scenario

### ISSUE THREAD

**Issue by sajid315** [the-canonizer/canonizer-3.0-api#640]
Steps to produce:
Given : User A is a direct supporter of the camp
And : User B(Supporter of camp) submitted (not committed) a change to the camp.
Then: User A removed support from camp
And: User B committed that change to the camp

User A is not a supporter when User B committed a change so User A will not have ability to agree and object. Also the change should go live directly in that case.

Currently its showing 1 out 1 is required.

![Image](https://user-images.githubusercontent.com/111273633/236158259-aa23b31a-518f-4bcd-b786-a57bc7f36e14.png)

**Comment by sajid315** [comment]
@M-Darab we need confirmation from @rupalichavan9860 as well on that case.

**Comment by rupalichavan9860** [comment]
@M-Darab @sajid315 Yes , Because user A is not a supporter at the time of change submission, the change should go live immediately.

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by rupalichavan9860** [comment]
Verified on live
