### ISSUE TITLE
Delayed in showing "Events" as compared to played "Event Line"

### ISSUE THREAD

**Issue by shahab-ramzan** [the-canonizer/canonizer-3.0-api#650]
As shown in attached screenshot below

![Image](https://user-images.githubusercontent.com/120023458/236385890-07832b98-b347-4687-ac83-381e747ebf9f.png)

**Comment by shahab-ramzan** [comment]
@sunilspr7  Can you please remove the initial event("latest timeline created") from eventline api? As we don't need to display it

**Comment by hassaanCD** [comment]
Fixed



![Image](https://github.com/the-canonizer/canonizer-3.0-api/assets/120023458/c9c936e5-8024-4bd0-a9f0-98c607b53260)
