### ISSUE TITLE
Bread crumb camps not all being included in emails

### ISSUE THREAD

**Issue by rohit-talentelgia** [the-canonizer/canonizer-3.0-api#665]
On may 13, 10:48 am MDT, an email went out containing the below html:

AS you can see only the **God / Transhumanist** camps in the breadcrumbs was included.
But it needs to include all the intermediate breadcrumbs camp also::
**God > Mother Nature > Theist > Monotheism > Christian > LDS > Transhumanist**

And every bread crumbs camp needs to be a link to that specific camp., including the link "God" camp, which is the name of the topic, but should be used instead of "agrement".

<html>
<body>

Hello Brent Allsop,
--
Conor-White-Sullivan has added their support to this camp: God / Transhumanist
You are receiving this e-mail because:You are subscribed to God

</body>
</html>

Hello Brent Allsop,
[Conor-White-Sullivan](https://egfggag.r.af.d.sendibt2.com/tr/cl/A9B03OVih_Y8nsilUYnUdnUc5QH0PhCdAA2mPiGUhoNFi5bS2F_qSZ7uCkJbm9Dsq23HZe9HYPrhUtvdW6D901JvqXACJdpIc4hu5zADjfF6c5cxZkJocvcaiCY4q6RDOAw4c6lF343HgOkndxgv1mJhEcY5Nn0e1estxTEFatk_psY0zD6xtxYbVl_Avu3eVkiXuXJXgkE2bBXo_1cFoop5-_m85G7fBg_yxxzMM7XWb6l4pB1f6clYMEX-FerZmX516t9Uqk0-ntX_Qh73niW0up62qpGRS-uvUdnJ15eXMXEzsj6DKzCSVhOkEMzQpcwBJy4J_wM) has added their support to this camp: [God / Transhumanist](https://egfggag.r.af.d.sendibt2.com/tr/cl/DPUuvOKRk3k_2uurjw3xhNNT9-fVVkZigjczxBFoJ4f3O9V-82Aga-JgM6q3QpojkLv-LAq7nwLSpNFfPKZ2MZ5Tl0gjLKyyEViegvnjzFNZD8JSQpJ4EbrmoES1RAYG8v2OQfPlK_gpQfoNW7bkl840o06LAw6OO3JwJAs0Jcte2SwISHLXkaYP3MfAVjqWFhlrl-6RlcCt4VL2PwD6YQ-Qh9Elma-LXoOBTV1hAs30hfsn5iKzR_1li6OFDEA_am8cz-vDjktC2d2nL4WmKP3J)

You are receiving this e-mail because:
You are subscribed to [God](https://egfggag.r.af.d.sendibt2.com/tr/cl/D7fDwx8qIRC36z0mhY7N6gyi3-FwISBkwUyX7d28e-fLImZCLUw935KFMePDOoTaUW7v2o-Mp7JzwX0nQnRrHtEiW0DcP-hh4zu9nQoVA5dkyxJ6upVEybZt3knrFW347wLmgCneyZzjCBgnEk0WNfRJvvA1Uw7w3914WgB7Y8jOa4vX6dgwsItaBjaPSGQefYvOTZraTto4QVZr7b8zKMxd3zizxTklm7FQffsWEH40yZvq080K-uV2FPPgIznqomyKXw)

**Comment by array-junkie** [comment]
@rupalichavan9860 Breadcrumbs will be changed for the following emails,

- supportRemovedMail
- supportAddedMail
- purposedToSupporters
- objectionToSubmitter
- ThankToSubmitterMail

Please verify and let us know if we need to change it anywhere else.
