### ISSUE TITLE
Update objection URL's for older activities

### ISSUE THREAD

**Issue by sajid315** [the-canonizer/canonizer-3.0-api#711]
As fixing done in following ticket for newer activities.
https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/issues/387

Now  As discussed with @rupalichavan9860 for older activities related to objection of camp change we need to write a script for database. And update URL's to redirect of camp history pages.

**Comment by rupalichavan9860** [comment]
Working fine on staging
