### ISSUE TITLE
Disable all subcamps in parent drop-down id parent is in review

### ISSUE THREAD

**Issue by nalwa** [the-canonizer/canonizer-3.0-api#720]
Steps : 
1.Create 3 camps “camp 1”,”camp 2”, and “camp 3” and support with User A
2.login with user B and change parent of camp 2 to camp 3 - in review 
3. Create sub camp of camp 2 
4. Try to change parent of camp 3

Actual : Sub camp of camp 2 is listing
Expected: Camp 2 is in review and disabled so sub camp should be disabled as well

**Comment by rupalichavan9860** [comment]
@nalwa I am getting "Something went wrong" error on step 2(while committing changes)
![image](https://github.com/the-canonizer/canonizer-3.0-api/assets/40416610/76e64612-a36e-4211-9215-0fed51ac87d7)

But above mentioned case is working fine so closing this and creating new ticket for error

**Comment by hassaanCD** [comment]
Working fine on live
