### ISSUE TITLE
On editing camp  statement not working correctly

### ISSUE THREAD

**Issue by nalwa** [the-canonizer/canonizer-3.0-api#722]
There is an issue in the update camp statement
The Parsed_value is not returning the updated value whereas the "value" has the updated value

Steps to replicate
1. Add a statement, submit statement
2. Click on Edit change (Do not commit changes)
3. Edit the previous statement and click submit statement
4. check the API response: https://api3.canonizer.com/api/v3/get-statement-history

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by hassaanCD** [comment]
Working fine on live
