### ISSUE TITLE
"Invalid date" error occur after creating new topic

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/canonizer-3.0-api#748]
As shown in attached screenshot below:

![Image](https://github.com/the-canonizer/canonizer-3.0-api/assets/120023458/1863cff7-bb8f-474f-b5cf-bd5e661096af)

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by rupalichavan9860** [comment]
Verified on live
