### ISSUE TITLE
Multiple support added in every subcamp after camp unarchive.

### ISSUE THREAD

**Issue by array-junkie** [the-canonizer/canonizer-3.0-api#753]
- Create a topic with "User A" and then create a sub-camp "C1" and support it. 
- Login with "User B" and create a sub-camp C11 under C1 and support it. (User A supports camp C1 and User B supports C11 which is the child of C1)
- Login with User C and submit a "Camp Archive" change in the "Agreement" camp & agree with both User A & B. The change will go live.
- Now again submit a "Camp Unarchive" change from user A. Change will go live immediately.

**Expected Result**: Support should be restored in the respective camps like User A's in C1 and User B's in C11.
**Actual Result**: Support of User A & B is restored in both C1 and C11.

**Comment by sandeeptlgt** [comment]
Closed, verified on staging.
