### ISSUE TITLE
Exclude topic_num and camp_num from user supports URL

### ISSUE THREAD

**Issue by sajid315** [the-canonizer/canonizer-3.0-api#828]
1. Open any topic on canonizer. 
2- In Support tree click on any nickname to check profile of a user. 
3- In includes topic and camp number in URL and at backend. 

Expected Results: It should not include topic and camp number in URL because its useless for getting user all supports. 

Following is the reference screenshot.
![image](https://github.com/the-canonizer/canonizer-3.0-api/assets/111273633/301de3c6-1e0b-4252-8c9a-0761e63f2966)

**Comment by sajid315** [comment]
@rupalichavan9860 please confirm above updates.

**Comment by sajid315** [comment]
@vikasranatalentelgia this ticket is not completed because the URL still have the topic_num and camp_num in different places. 
https://development.canonizer.com/user/supports/85?topicnum=10&campnum=1&canon=8

As you can see that support tree also have this URL (also this URL can be in other places as well),
![image](https://github.com/the-canonizer/canonizer-3.0-api/assets/111273633/e14e8da2-32a3-4a02-9285-74fde2f71a95)

**Comment by subhancd** [comment]
verified on dev

**Comment by akashgit77** [comment]
working fine on the production.
