### ISSUE TITLE
Include Older and Newer Changes in Email Template + Improvements of template

### ISSUE THREAD

**Issue by sajid315** [the-canonizer/canonizer-3.0-api#844]

**Comment by array-junkie** [comment]
@BrentAllsop, @rupalichavan9860,
As per the discussion in the last meeting, We have created 3 email templates for propose a change in topic/camp. 

Following are the scenario to send email for change propose,

**Scenario 1:** 
A non-supporter user proposes a change in topic/camp that will go **_In-Review_** and the email will be sent to all supporters of that topic/camp. For that case Figma design is attached below.

**Scenario 2:**
User is a single supporter of a camp and he proposes a change that will go live immediately. Do we need to send an email of the proposed change to him (currently the email going) ? 
If yes then both email templates will be the same for scenario 1 & 2? 

https://www.figma.com/file/zRedRMt1EslDv8agTzXUMl/Canonizer?type=design&node-id=1850%3A59&mode=design&t=YY9Kvuhp4ry8DNX8-1

**Comment by array-junkie** [comment]
@BrentAllsop, @rupalichavan9860 we have updated the email templates as per the discussion in the last meeting. There are 3 templates: 
- Template for statement change
- Template for camp change
- Template for topic change

Kindly take a look.

**Comment by sajid315** [comment]
@M-Darab  As discussed in morning scrum call of 30 November 2023 we need to do following updates:
1- We need to make sure each breadcrumb should be a link.
2- Each breadcrumb arrow icon needs to be same.
3- Exclude the Agreement camp from email when the change is done in topic.

**Comment by sajid315** [comment]
@M-Darab Agreement camp needs to be excluded only for topic email as mentioned in point number 3 above. 
But currently its not coming for all emails. Have a look please.

![image](https://github.com/the-canonizer/canonizer-3.0-api/assets/111273633/a8a33b02-14d6-4067-8933-0636c72c61e1)

**Comment by array-junkie** [comment]
Following the discussion during today's meeting, Brent recommended modifying the "proposed a change" email template to replace the "Enabled/Disabled" options for "Disable additional sub-camps" and "Single level camps only" with the binary selection of "Yes" or "No".

PR [#883](https://github.com/the-canonizer/canonizer-3.0-api/pull/883)
