### ISSUE TITLE
Make a new API for "Camp Archive Check" On Topic/Camp/Statement history pages and remove GET API

### ISSUE THREAD

**Issue by array-junkie** [the-canonizer/canonizer-3.0-api#863]

**Comment by array-junkie** [comment]
As per the discussion with @ks-rahul and @vikasranatalentelgia, GET API is utilized to check the following live camp statuses on the topic/camp/statement history pages:

- Camp Archive 
- Disable additional subcamps
- Single level sub camps only

So we are making a new API for the above-mentioned statuses rather than utilizing GET API.

**Comment by array-junkie** [comment]
Backend PR Raised: [#867](https://github.com/the-canonizer/canonizer-3.0-api/pull/867)

**Comment by DevAlchemyCD** [comment]
Frontend PR Raised: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1432

**Comment by DevAlchemyCD** [comment]
In this case, it is not working:
1: create a topic with user 1
2: create camp1 with user1 and support the camp.
3: archive camp1 with user2
4: agree with change with user1 
5: refresh the page the unarchive button is disabled

**Comment by array-junkie** [comment]
We have eliminated the check_camp_status API and the Get API from the topic/camp/statement history pages.

**Comment by DevAlchemyCD** [comment]
pr from frontend : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1457
