### ISSUE TITLE
Remove and Replace Nickname to User Obfuscation with Foreign Key

### ISSUE THREAD

**Issue by array-junkie** [the-canonizer/canonizer-3.0-api#878]
An old design requirement led to the implementation of an obfuscated relationship between private nicknames and their users. This obfuscation does not hide the relationship, does not slow an attacker and only adds overhead and complexity.

### Database Migration Requirements

Examples given for clarity

1. Add "user" column to nicknames table:
   - This column will store the user ID associated with each nickname.
   - Add the column after the existing "owner_code" column.

```
ALTER TABLE nicknames
ADD COLUMN user INT AFTER owner_code;
```

2. Make "user" a foreign key:
   - Define a foreign key constraint on the "user" column referencing the "id" column in the "users" table.
   - This ensures referential integrity and allows for efficient data retrieval.

```
ALTER TABLE nicknames
ADD CONSTRAINT fk_nicknames_user
FOREIGN KEY (user_id) REFERENCES users(id);
```

```
public function up()
{
    Schema::table('nicknames', function (Blueprint $table) {
        $table->integer('user_id')->after('owner_code');
        $table->foreign('user_id')->references('id')->on('users');
    });
}

public function down()
{
    Schema::table('nicknames', function (Blueprint $table) {
        $table->dropColumn('user_id');
        $table->dropForeign('nicknames_user_foreign');
    });
}
```

3. Populate "user" column:
   - For all records in the "nicknames" table.
   - Extract the user ID from each "owner_code" by:
   - Base64 decoding the code.
   - Extracting the substring between two occurrences of "example".
   - Converting the extracted string to an integer.
   - Update each nickname record with the extracted user ID in the "user" column.

```
UPDATE nicknames
SET user_id = CAST(SUBSTRING(BASE64_DECODE(owner_code), 5, LENGTH(BASE64_DECODE(owner_code)) - 10) AS UNSIGNED);
```

```
public function up()
{
    DB::table('nicknames')->update([
        'user' => DB::raw("CAST(SUBSTRING(BASE64_DECODE(owner_code), 5, LENGTH(BASE64_DECODE(owner_code)) - 10) AS UNSIGNED)")
    ]);
}
```

4. Drop owner_code

### canonizer-3.0-api Requirements

1. Remove canon_endcode and canon_decode from General library and Helpers
2. Remove and replace all instances of getUserByNickName method call

**Comment by sajid315** [comment]
With reference to update in above requirements and replace the "owner_code" with "user_id", we need following changes to do and tested,
1- Remove the encode and decode helpers for API repository and Service repository.
2- Making of a script to decode and populate older records owner code.
3- Track the "owner_code" at all places in code-base and replace it with "user_id" column.
4- Must need to verify raw queries and eloquent queries using "owner_code".
5- Scenario's needed to be handle for file upload module and unit test cases.
6- Need to verify emails that are using Nicknames as reference point to user.
7- Some of the stored procedure will also be update as "owner_code" used in these.
