### ISSUE TITLE
Change File Paths to relative path

### ISSUE THREAD

**Issue by sajid315** [the-canonizer/canonizer-3.0-api#889]
Identified the data storage in database that our file paths are completely stored in database that can cause issue. 
So as discussed we need to change these URL's to relative one to avoid future problems.

![Image](https://github.com/the-canonizer/canonizer-3.0-api/assets/111273633/52c891ec-e416-4016-860a-83b60514967c)

**Comment by sajid315** [comment]
@wahaj-hafeez I have made script to update the absolute path to relative one's. We need updates from frontend as well to append base URL's. So meanwhile you can work on it from UI side of upload module.

**Comment by DevAlchemyCD** [comment]
Pr form frontend : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1488
