### ISSUE TITLE
Only my topics checkbox unchecks on refresh

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/canonizer-3.0-api#923]
Steps:

1. Go to browse
2. Check"only my topics"
3. No refresh the page

Actual result: The check box unchecks
Expected result: The check box should remain checked

**Comment by saniatg** [comment]
Not fixed @ks-rahul

**Comment by ks-rahul** [comment]
@saniatg pr is still not merged

**Comment by rupalichavan9860** [comment]
Working fine on development server

**Comment by saniatg** [comment]
working fine on production
