### ISSUE TITLE
Multiple topic and camp creation on specific scenario

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/canonizer-3.0-api#958]
Steps to Reproduce:
Login and click on "create topic" button
Enter Topic name in "Topic Name" field
Press and hold the enter key
Observe the network call
As shown in attached screenshots:
![Screenshot_11](https://github.com/the-canonizer/canonizer-3.0-api/assets/120023458/d8336cea-9f17-4637-aa46-0ca128d87ae1)
![Screenshot_12](https://github.com/the-canonizer/canonizer-3.0-api/assets/120023458/158d19df-dc6c-4a11-b0b7-8e06dc2c0fb0)
![Screenshot_13](https://github.com/the-canonizer/canonizer-3.0-api/assets/120023458/8258e2c0-1003-43e7-90cd-da00d99e3dde)
![Screenshot_14](https://github.com/the-canonizer/canonizer-3.0-api/assets/120023458/c9eaaa27-571c-4e29-928b-ddf157de4002)

**Comment by DevAlchemyCD** [comment]
pr : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1635
