### ISSUE TITLE
Multiple API calling on "Enter" key hold

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/canonizer-3.0-api#966]
Steps to Reproduce:
Login with any user and select any topic
Click on "Camp Forum" button and navigate to "Camp Forum" page
Click on "Create Thread" 
Type any title in "Title" field and click on "Enter" button multiple times

Multiple calls lead to multiple confirmation and error messages as shown in attached screenshot:

![Image](https://github.com/the-canonizer/canonizer-3.0-api/assets/120023458/f605834e-c6f7-4bdc-a70d-ac605e7d2917)

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1657

**Comment by hassaanCD** [comment]
Working fine on development

**Comment by hassaanCD** [comment]
Working fine on production
