### ISSUE TITLE
Topic creation: Multiple API calling on "Enter" key hold

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/canonizer-3.0-api#974]
Multiple calls lead to multiple "Save" messages as shown in attached screenshot:

![Image](https://github.com/the-canonizer/canonizer-3.0-api/assets/120023458/95949922-e0a8-4de9-aeb0-e366f5697cb8)

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1690

**Comment by hassaanCD** [comment]
Working fine on development

**Comment by hassaanCD** [comment]
Working fine on production
